# This file is for setting up the Skywatch Automod service using Docker Compose.
#
# Before running `docker compose up`, you need to:
# 1. Create a `.env` file with your configuration. See the README.md for details.
# 2. (Optional but recommended) Create an empty `cursor.txt` file in this directory
#    to ensure Docker mounts a file, not a directory.
#    On Linux/macOS: touch cursor.txt
#
version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: skywatch-redis
    restart: unless-stopped

    # Expose Redis port for debugging (optional, remove in production)
    ports:
      - "6379:6379"

    # Persist Redis data
    volumes:
      - redis-data:/data

    # Redis configuration
    command: redis-server --appendonly yes --appendfsync everysec

    # Health check
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

  automod:
    # Build the Docker image from the Dockerfile in the current directory.
    build: .
    container_name: skywatch-automod

    # Restart the container automatically if it stops unexpectedly.
    restart: unless-stopped

    # Wait for Redis to be healthy before starting
    depends_on:
      redis:
        condition: service_healthy

    # Expose the metrics server port to the host machine.
    ports:
      - "4100:4101"

    # Load environment variables from a .env file in the same directory.
    # This is where you should put your BSKY_HANDLE, BSKY_PASSWORD, etc.
    env_file:
      - .env

    # Override REDIS_URL to use the Redis service
    environment:
      - REDIS_URL=redis://redis:6379

    # Mount a volume to persist the firehose cursor.
    # This links the `cursor.txt` file from your host into the container at `/app/cursor.txt`.
    # Persisting this file allows the automod to resume from where it left off
    # after a restart, preventing it from reprocessing old events or skipping new ones.
    # Also persist session.json to avoid hitting login rate limits.
    volumes:
      - ./cursor.txt:/app/cursor.txt
      - ./session.json:/app/session.json

volumes:
  redis-data:
