name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Setup example config files for CI
        run: |
          cp rules/constants.example.ts rules/constants.ts
          cp rules/handles.example.ts rules/handles.ts
          cp rules/posts.example.ts rules/posts.ts
          cp rules/profiles.example.ts rules/profiles.ts
          cp rules/accountAge.example.ts rules/accountAge.ts
          cp rules/accountThreshold.example.ts rules/accountThreshold.ts

      - name: Run linter
        run: bun run lint

      - name: Type check
        run: bun run type-check

      - name: Run tests
        run: bun run test:run

      - name: Generate coverage report
        run: bun run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/coverage-final.json
          fail_ci_if_error: false
          verbose: true
